FROM python:3.11-slim
LABEL maintainer="Linus Torvalds" description="This is description" version="1.0.0"
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 APP_VERSION=1.0.0 ENVIRONMENT=prod STUDENT_NAME=Ilya
WORKDIR /app
COPY . .
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc && \
    pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    apt-get purge -y --auto-remove gcc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    groupadd -g 1001 usergroup && \
    useradd -u 1001 -g usergroup user && \
    chown -R 1001:1001 /app
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')" || exit 1
USER 1001
EXPOSE 8080
CMD ["python", "app.py"]