FROM python:3.11-slim
WORKDIR /app
LABEL maintainer="Linus Torvalds" description="This is description" version="1.0.0"
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        curl \
        wget \
        git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s \
  CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8080')" || exit 1
RUN groupadd -g 1001 usergroup && \
    useradd -u 1001 -g usergroup user && \
    chown -R 1001:1001 /app
USER 1001
EXPOSE 8080
CMD ["python", "app.py"]